version: "3"

services:
  app:
    image: node:latest
    tty: true
    restart: on-failure:5
    working_dir: /home/tabletoptracker-client-vue/app
    entrypoint: /entrypoint.sh
    ports:
      - ${CLIENT_PORT}:80
      - ${CLIENT_PORT_DEV}:8080
    volumes:
      - ./:/home/tabletoptracker-client-vue
      - ./entrypoint.sh:/entrypoint.sh
    